Repository michelin/kafkactl, pull requests merged in 2023-10, with the labels that each got.

#71 Add GitHub Actions for tagging
  .github/workflows/tag.yml
Labels: enhancement

#68 Manage Confluent Cloud tags
  README.md
Labels: documentation

#75 Fix tag job
  .github/workflows/tag.yml
Labels: bug

#76 Add Check Style
  .checkstyle/checkstyle.xml
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  CONTRIBUTING.md
  build.gradle
  src/test/java/com/michelin/kafkactl/ApiResourcesSubcommandTest.java
  src/test/java/com/michelin/kafkactl/ApplySubcommandTest.java
  src/test/java/com/michelin/kafkactl/ConfigSubcommandTest.java
  src/test/java/com/michelin/kafkactl/ConnectClustersSubcommandTest.java
  src/test/java/com/michelin/kafkactl/ConnectorsSubcommandTest.java
  src/test/java/com/michelin/kafkactl/DeleteRecordsSubcommandTest.java
  src/test/java/com/michelin/kafkactl/DeleteSubcommandTest.java
  src/test/java/com/michelin/kafkactl/DiffSubcommandTest.java
  src/test/java/com/michelin/kafkactl/GetSubcommandTest.java
  src/test/java/com/michelin/kafkactl/ImportSubcommandTest.java
  src/test/java/com/michelin/kafkactl/KafkactlCommandTest.java
  src/test/java/com/michelin/kafkactl/KafkactlConfigTest.java
  src/test/java/com/michelin/kafkactl/ResetOffsetsSubcommandTest.java
  src/test/java/com/michelin/kafkactl/SchemaSubcommandTest.java
  src/test/java/com/michelin/kafkactl/UsersSubcommandTest.java
  src/test/java/com/michelin/kafkactl/services/ConfigServiceTest.java
  src/test/java/com/michelin/kafkactl/services/FileServiceTest.java
  src/test/java/com/michelin/kafkactl/services/FormatServiceTest.java
  src/test/java/com/michelin/kafkactl/services/LoginServiceTest.java
  src/test/java/com/michelin/kafkactl/services/ResourceServiceTest.java
  src/test/java/com/michelin/kafkactl/services/SystemServiceTest.java
  src/test/java/com/michelin/kafkactl/utils/VersionProviderTest.java
Labels: enhancement
