Repository michelin/kafkactl, pull requests merged in 2025-08, with the labels that each got.

#248 Bump Micronaut HTTP Client to 4.9.10
  build.gradle
Labels: dependencies

#249 Run Sonar scan before Grype
  .github/workflows/build.yml
Labels: ci/cd

#251 Add the possibility to import specific resources
  README.md
  src/main/java/com/michelin/kafkactl/client/NamespacedResourceClient.java
  src/main/java/com/michelin/kafkactl/command/Delete.java
  src/main/java/com/michelin/kafkactl/command/Import.java
  src/main/java/com/michelin/kafkactl/service/ResourceService.java
  src/test/java/com/michelin/kafkactl/command/ImportTest.java
  src/test/java/com/michelin/kafkactl/service/resource/ResourceServiceTest.java
Labels: feature
