Repository michelin/kafkactl, pull requests merged in 2025-01, with the labels that each got.

#178 Add logo
  .readme/logo.svg
  README.md
Labels: documentation

#172 Add documentation for secured namespaces
  README.md
Labels: documentation

#179 Build Kafkactl for MacOS
  .github/workflows/hotfix.yml
  .github/workflows/pull_request.yml
  .github/workflows/push_main.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
Labels: feature

#182 Fix sonar tests link in README
  README.md
Labels: documentation

#180 Add search option for get namespace command
  README.md
  src/main/java/com/michelin/kafkactl/client/ClusterResourceClient.java
  src/main/java/com/michelin/kafkactl/client/NamespacedResourceClient.java
  src/main/java/com/michelin/kafkactl/command/Connector.java
  src/main/java/com/michelin/kafkactl/command/Get.java
  src/main/java/com/michelin/kafkactl/service/FormatService.java
  src/main/java/com/michelin/kafkactl/service/ResourceService.java
  src/test/java/com/michelin/kafkactl/command/ConnectorTest.java
  src/test/java/com/michelin/kafkactl/command/GetTest.java
  src/test/java/com/michelin/kafkactl/service/FormatServiceTest.java
  src/test/java/com/michelin/kafkactl/service/ResourceServiceTest.java
Labels: feature

#181 Add yml output option
  README.md
  src/main/java/com/michelin/kafkactl/command/ApiResources.java
  src/main/java/com/michelin/kafkactl/command/Connector.java
  src/main/java/com/michelin/kafkactl/command/Get.java
  src/main/java/com/michelin/kafkactl/command/ResetPassword.java
  src/main/java/com/michelin/kafkactl/command/Schema.java
  src/main/java/com/michelin/kafkactl/command/auth/AuthInfo.java
  src/main/java/com/michelin/kafkactl/command/config/ConfigCurrentContext.java
  src/main/java/com/michelin/kafkactl/command/config/ConfigGetContexts.java
  src/main/java/com/michelin/kafkactl/model/Output.java
  src/main/java/com/michelin/kafkactl/service/FormatService.java
  src/main/java/com/michelin/kafkactl/service/ResourceService.java
  src/test/java/com/michelin/kafkactl/command/ApiResourcesTest.java
  src/test/java/com/michelin/kafkactl/command/ConnectorTest.java
  src/test/java/com/michelin/kafkactl/command/GetTest.java
  src/test/java/com/michelin/kafkactl/command/ResetPasswordTest.java
  src/test/java/com/michelin/kafkactl/command/SchemaTest.java
  src/test/java/com/michelin/kafkactl/command/auth/AuthInfoTest.java
  src/test/java/com/michelin/kafkactl/command/config/ConfigCurrentContextTest.java
  src/test/java/com/michelin/kafkactl/command/config/ConfigGetContextsTest.java
  src/test/java/com/michelin/kafkactl/service/FormatServiceTest.java
  src/test/java/com/michelin/kafkactl/service/ResourceServiceTest.java
Labels: enhancement

#186 Fix random order in NoResource message display
  src/main/java/com/michelin/kafkactl/service/FormatService.java
  src/test/java/com/michelin/kafkactl/service/FormatServiceTest.java
Labels: bug
