Repository michelin/kafkactl, pull requests merged in 2025-03, with the labels that each got.

#202 Set tab to space in Palantir format
  build.gradle
Labels: ci/cd

#204 Bump to Micronaut 4.7.6 and Gradle 8.11.1
  .github/workflows/release.yml
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#194 Build Kafkactl statically with Musl
  .github/workflows/hotfix.yml
  .github/workflows/pull_request.yml
  .github/workflows/push_main.yml
  .github/workflows/release.yml
  build.gradle
Labels: feature

#205 Add Grype scan
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/push_main.yml
  .github/workflows/release.yml
  build.gradle
Labels: ci/cd
